#file: noinspection SwYamlUnresolvedReferencesInspection
openapi: 3.0.3
info:
  title: REST API сервер для ПГУТИ
  version: 0.0.1
  description: >
    краткое описание приложения

servers:
  - url: http://localhost:8080

paths:
  /api/v1/login:
    post:
      summary: Аутенфикация пользователя
      operationId: "Login"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Login'
      responses:
        '200':
          description: Успешная операция
        '400':
          description: Неверный запрос
        '401':
          description: Неавторизирован
        '500':
          description: Внутренняя ошибка
  /api/v1/MyInfo:
    get:
      summary: Получение информации о себе
      operationId: MyInfo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Login'
      responses:
        '200':
          description: Данные получены
        '401':
          description: Пользователь не авторизован
        '500':
          description: Внутренняя ошибка
  /api/v1/AddInfo:
    put:
      summary: Добавить информацию о себе
      operationId: MyInfo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Login'
      responses:
        '201':
          description: Данные добавлены
        '401':
          description: Неавторизирован
        '500':
          description: Внутренняя ошибка
  /api/v1/DeleteInfo:
    delete:
      summary: Удалить информацию о себе
      operationId: MyInfo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Login'
      responses:
        '200':
          description: Данные удалены
        '401':
          description: Пользователь не авторизован
        '500':
          description: Внутренняя ошибка


components:
  schemas:
    Login:
      type: object
      properties:
        login:
          type: string
          example: login
        password:
          type: string
          example: password
